In [1]:
import pandas as pd
import altair as alt

In [2]:
#amsterdam 
df_amsterdam_weekdays = pd.read_csv("amsterdam_weekdays.csv")
df_amsterdam_weekends = pd.read_csv("amsterdam_weekends.csv")

#athens
df_athens_weekdays = pd.read_csv("athens_weekdays.csv")
df_athens_weekends = pd.read_csv("athens_weekends.csv")

#barcelona
df_barcelona_weekdays = pd.read_csv("barcelona_weekdays.csv")
df_barcelona_weekends = pd.read_csv("barcelona_weekends.csv")

#london
df_london_weekdays = pd.read_csv("london_weekdays.csv")
df_london_weekends = pd.read_csv("london_weekends.csv")

#paris
df_paris_weekdays = pd.read_csv("paris_weekdays.csv")
df_paris_weekends = pd.read_csv("paris_weekends.csv")

#rome
df_rome_weekdays = pd.read_csv("rome_weekdays.csv")
df_rome_weekends = pd.read_csv("rome_weekends.csv")

data notes
amsterdam: biggest differce between weekday and weekend, cheaper weakday (need to confirm), amsterdam most bedrooms, most expeive
athens: Cleanliness, Satisfaction, capacity, cheapest 
barcelona: lowest capacity
london: lowest satisfaction
paris: lowest bedroom, lowest metro distance, cheaper weekend
rome: most superhost

In [3]:
data = [["Amsterdam", "Weekdays", round(df_amsterdam_weekdays["realSum"].mean(), 2)],
       ["Amsterdam", "Weekends", round(df_amsterdam_weekends["realSum"].mean(), 2)],
       ["Athens", "Weekdays", round(df_athens_weekdays["realSum"].mean(), 2)],
       ["Athens", "Weekends", round(df_athens_weekends["realSum"].mean(), 2)],
       ["Barcelona", "Weekdays", round(df_barcelona_weekdays["realSum"].mean(), 2)],
       ["Barcelona", "Weekends", round(df_barcelona_weekends["realSum"].mean(), 2)],
       ["London", "Weekdays", round(df_london_weekdays["realSum"].mean(), 2)],
       ["London", "Weekends", round(df_london_weekends["realSum"].mean(), 2)],
       ["Paris", "Weekdays", round(df_paris_weekdays["realSum"].mean(), 2)],
       ["Paris", "Weekends", round(df_paris_weekends["realSum"].mean(), 2)],
       ["Rome", "Weekdays", round(df_rome_weekdays["realSum"].mean(), 2)],
       ["Rome", "Weekends", round(df_rome_weekends["realSum"].mean(), 2)]]

df_format = pd.DataFrame(data, columns=['City', 'Period', "Average_Price"])
df_format

         City    Period  Average_Price
0   Amsterdam  Weekdays         545.02
1   Amsterdam  Weekends         604.83
2      Athens  Weekdays         155.87
3      Athens  Weekends         147.58
4   Barcelona  Weekdays         288.39
5   Barcelona  Weekends         300.28
6      London  Weekdays         360.23
7      London  Weekends         364.39
8       Paris  Weekdays         398.79
9       Paris  Weekends         387.03
10       Rome  Weekdays         201.62
11       Rome  Weekends         209.13

In [4]:
df_format = df_format.sort_values(by=["Average_Price"])

weekday =  alt.Chart(df_format).mark_().encode(
    x = "City",
    y = "Average_Price",
    color = alt.value("blue")
).transform_filter(
    alt.FieldEqualPredicate(field='Period', equal="Weekdays")
)

weekdend =  alt.Chart(df_format).mark_line().encode(
    x = "City",
    y = "Average_Price",
    color = alt.value("red")
).transform_filter(
    alt.FieldEqualPredicate(field='Period', equal="Weekends")
)
weekdend + weekday

AttributeError: 'Chart' object has no attribute 'mark_'

In [ ]:
data_superhost = [["Amsterdam", df_amsterdam_weekdays['host_is_superhost'].value_counts()[True] + df_amsterdam_weekends['host_is_superhost'].value_counts()[True]],
                  ["Athens", df_athens_weekdays['host_is_superhost'].value_counts()[True] + df_athens_weekends['host_is_superhost'].value_counts()[True]],
                  ["Barcelona", df_barcelona_weekdays['host_is_superhost'].value_counts()[True] + df_barcelona_weekends['host_is_superhost'].value_counts()[True]],
                  ["London", df_london_weekdays['host_is_superhost'].value_counts()[True] + df_london_weekends['host_is_superhost'].value_counts()[True]],
                  ["Paris", df_paris_weekdays['host_is_superhost'].value_counts()[True] + df_paris_weekends['host_is_superhost'].value_counts()[True]],
                  ["Rome", df_rome_weekdays['host_is_superhost'].value_counts()[True] + df_rome_weekends['host_is_superhost'].value_counts()[True]]]

df_superhost = pd.DataFrame(data_superhost, columns=['City', "Superhost_Count"])
df_superhost = df_superhost.sort_values(by=['Superhost_Count'], ascending=False)
df_superhost

In [ ]:
from statistics import mean

data_cleanliness = [["Amsterdam", mean([df_amsterdam_weekdays['cleanliness_rating'].mean(), df_amsterdam_weekends['cleanliness_rating'].mean()])],
                    ["Athens", mean([df_athens_weekdays['cleanliness_rating'].mean(), df_athens_weekends['cleanliness_rating'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['cleanliness_rating'].mean(), df_barcelona_weekends['cleanliness_rating'].mean()])],
                    ["London", mean([df_london_weekdays['cleanliness_rating'].mean(), df_london_weekends['cleanliness_rating'].mean()])],
                    ["Paris", mean([df_paris_weekdays['cleanliness_rating'].mean(), df_paris_weekends['cleanliness_rating'].mean()])],
                    ["Rome", mean([df_rome_weekdays['cleanliness_rating'].mean(), df_rome_weekends['cleanliness_rating'].mean()])]]

df_cleanliness = pd.DataFrame(data_cleanliness, columns=['City', "Cleanliness"])
df_cleanliness = df_cleanliness.sort_values(by=['Cleanliness'], ascending=False)
df_cleanliness

In [ ]:
data_bedrooms = [["Amsterdam", mean([df_amsterdam_weekdays['bedrooms'].mean(), df_amsterdam_weekends['bedrooms'].mean()])],
                    ["Athens", mean([df_athens_weekdays['bedrooms'].mean(), df_athens_weekends['bedrooms'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['bedrooms'].mean(), df_barcelona_weekends['bedrooms'].mean()])],
                    ["London", mean([df_london_weekdays['bedrooms'].mean(), df_london_weekends['bedrooms'].mean()])],
                    ["Paris", mean([df_paris_weekdays['bedrooms'].mean(), df_paris_weekends['bedrooms'].mean()])],
                    ["Rome", mean([df_rome_weekdays['bedrooms'].mean(), df_rome_weekends['bedrooms'].mean()])]]

df_bedrooms = pd.DataFrame(data_bedrooms, columns=['City', "Avg_Bedroom"])
df_bedrooms = df_bedrooms.sort_values(by=['Avg_Bedroom'], ascending=False)
df_bedrooms

In [ ]:
data_satisfaction = [["Amsterdam", mean([df_amsterdam_weekdays['guest_satisfaction_overall'].mean(), df_amsterdam_weekends['guest_satisfaction_overall'].mean()])],
                    ["Athens", mean([df_athens_weekdays['guest_satisfaction_overall'].mean(), df_athens_weekends['guest_satisfaction_overall'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['guest_satisfaction_overall'].mean(), df_barcelona_weekends['guest_satisfaction_overall'].mean()])],
                    ["London", mean([df_london_weekdays['guest_satisfaction_overall'].mean(), df_london_weekends['guest_satisfaction_overall'].mean()])],
                    ["Paris", mean([df_paris_weekdays['guest_satisfaction_overall'].mean(), df_paris_weekends['guest_satisfaction_overall'].mean()])],
                    ["Rome", mean([df_rome_weekdays['guest_satisfaction_overall'].mean(), df_rome_weekends['guest_satisfaction_overall'].mean()])]]

df_satisfaction = pd.DataFrame(data_satisfaction, columns=['City', "avg_satisfaction"])
df_satisfaction = df_satisfaction.sort_values(by=['avg_satisfaction'], ascending=False)
df_satisfaction

In [ ]:
data_capacity = [["Amsterdam", mean([df_amsterdam_weekdays['person_capacity'].mean(), df_amsterdam_weekends['person_capacity'].mean()])],
                    ["Athens", mean([df_athens_weekdays['person_capacity'].mean(), df_athens_weekends['person_capacity'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['person_capacity'].mean(), df_barcelona_weekends['person_capacity'].mean()])],
                    ["London", mean([df_london_weekdays['person_capacity'].mean(), df_london_weekends['person_capacity'].mean()])],
                    ["Paris", mean([df_paris_weekdays['person_capacity'].mean(), df_paris_weekends['person_capacity'].mean()])],
                    ["Rome", mean([df_rome_weekdays['person_capacity'].mean(), df_rome_weekends['person_capacity'].mean()])]]

df_capacity = pd.DataFrame(data_capacity, columns=['City', "avg_capacity"])
df_capacity = df_capacity.sort_values(by=['avg_capacity'], ascending=False)
df_capacity

In [ ]:
data_capacity_2 = [["Amsterdam", df_amsterdam_weekdays['person_capacity'].mean()],
                    ["Athens", df_athens_weekdays['person_capacity'].mean()],
                    ["Barcelona", df_barcelona_weekdays['person_capacity'].mean()],
                    ["London", df_london_weekdays['person_capacity'].mean()],
                    ["Paris", df_paris_weekdays['person_capacity'].mean()],
                    ["Rome", df_rome_weekdays['person_capacity'].mean()]]

df_capacity_2 = pd.DataFrame(data_capacity_2, columns=['City', "avg_capacity"])
df_capacity_2 = df_capacity_2.sort_values(by=['avg_capacity'], ascending=False)
df_capacity_2

In [ ]:
data_metro = [["Amsterdam", mean([df_amsterdam_weekdays['metro_dist'].mean(), df_amsterdam_weekends['metro_dist'].mean()])],
                    ["Athens", mean([df_athens_weekdays['metro_dist'].mean(), df_athens_weekends['metro_dist'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['metro_dist'].mean(), df_barcelona_weekends['metro_dist'].mean()])],
                    ["London", mean([df_london_weekdays['metro_dist'].mean(), df_london_weekends['metro_dist'].mean()])],
                    ["Paris", mean([df_paris_weekdays['metro_dist'].mean(), df_paris_weekends['metro_dist'].mean()])],
                    ["Rome", mean([df_rome_weekdays['metro_dist'].mean(), df_rome_weekends['metro_dist'].mean()])]]

df_metro = pd.DataFrame(data_metro, columns=['City', "avg_metro_dist"])
df_metro = df_metro.sort_values(by=['avg_metro_dist'])
df_metro

In [ ]:
data_price = [["Amsterdam", mean([df_amsterdam_weekdays['realSum'].mean(), df_amsterdam_weekends['realSum'].mean()])],
                    ["Athens", mean([df_athens_weekdays['realSum'].mean(), df_athens_weekends['realSum'].mean()])],
                    ["Barcelona", mean([df_barcelona_weekdays['realSum'].mean(), df_barcelona_weekends['realSum'].mean()])],
                    ["London", mean([df_london_weekdays['realSum'].mean(), df_london_weekends['realSum'].mean()])],
                    ["Paris", mean([df_paris_weekdays['realSum'].mean(), df_paris_weekends['realSum'].mean()])],
                    ["Rome", mean([df_rome_weekdays['realSum'].mean(), df_rome_weekends['realSum'].mean()])]]

df_price = pd.DataFrame(data_price, columns=['City', "price_avg"])
df_price = df_price.sort_values(by=['price_avg'])
df_price

In [ ]:
data_price_diff = [["Amsterdam", df_amsterdam_weekdays['realSum'].mean() - df_amsterdam_weekends['realSum'].mean()],
                  ["Athens", df_athens_weekdays['realSum'].mean() - df_athens_weekends['realSum'].mean()],
                  ["Barcelona", df_barcelona_weekdays['realSum'].mean() - df_barcelona_weekends['realSum'].mean()],
                  ["London", df_london_weekdays['realSum'].mean() - df_london_weekends['realSum'].mean()],
                  ["Paris", df_paris_weekdays['realSum'].mean() - df_paris_weekends['realSum'].mean()],
                  ["Rome", df_rome_weekdays['realSum'].mean() - df_rome_weekends['realSum'].mean()]]

df_price_diff = pd.DataFrame(data_price_diff, columns=['City', "ave_price_diff"])
df_price_diff = df_price_diff.sort_values(by=['ave_price_diff'], ascending=False)
df_price_diff

In [ ]:
alt.Chart(df_price).mark_bar().encode(
    x = alt.X("City", sort="-y", axis=alt.Axis(labelAngle=-45)),
    y = alt.Y("price_avg", axis=alt.Axis(title="Average Price (USD$)")),
    color = alt.value("#ff625e")
).properties(
    width =250,
    height = 350
)

In [5]:
# real sum is the price for 2 people for 2 nights so the price per person per night would be the real sum divied by 4
df_amsterdam_weekdays["price_per_person"] = df_amsterdam_weekdays["realSum"] / 4
df_athens_weekdays["price_per_person"] = df_athens_weekdays["realSum"] / 4
df_barcelona_weekdays["price_per_person"] = df_barcelona_weekdays["realSum"] / 4
df_london_weekdays["price_per_person"] = df_london_weekdays["realSum"] / 4
df_paris_weekdays["price_per_person"] = df_paris_weekdays["realSum"] / 4
df_rome_weekdays["price_per_person"] = df_rome_weekdays["realSum"] / 4

data_price_per_person = [["Amsterdam", df_amsterdam_weekdays['price_per_person'].mean()],
                  ["Athens", df_athens_weekdays['price_per_person'].mean()],
                  ["Barcelona", df_barcelona_weekdays['price_per_person'].mean()],
                  ["London", df_london_weekdays['price_per_person'].mean()],
                  ["Paris", df_paris_weekdays['price_per_person'].mean()],
                  ["Rome", df_rome_weekdays['price_per_person'].mean()]]

df_price_per_person = pd.DataFrame(data_price_per_person, columns=['City', "Price per person"])
df_price_per_person = df_price_per_person.sort_values(by=['Price per person'], ascending=False)
df_price_per_person

        City  Price per person
0  Amsterdam        136.255132
4      Paris         99.696670
3     London         90.057587
2  Barcelona         72.097917
5       Rome         50.404513
1     Athens         38.966745

In [6]:
alt.Chart(df_price_per_person).mark_bar().encode(
    x = alt.X("City", sort="-y", axis=alt.Axis(labelAngle=-45)),
    y = alt.Y("Price per person", axis=alt.Axis(title="Price per person (USD$)")),
    color = alt.value("#ff526e")
).properties(
    width =250,
    height = 350,
    title="Price per person for one night"
)

alt.Chart(...)